create table histories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid not null,
  media_type varchar not null,
  media_id varchar not null,
  duration bigint not null,
  title varchar,
  route varchar not null,
  watched bigint,
  poster varchar,
  overview text,
  season varchar,
  episode varchar
);