#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# check eslint standards
yarn check:lint || (
  echo "Please lint your code";
  false;
)

# check prettier standards
yarn check:format || (
  echo "Please format your code";
  false;
)
